"""add role to sessions

Revision ID: df5f6d8224af
Revises: e8e612087328
Create Date: 2025-10-28 19:22:33.941108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df5f6d8224af'
down_revision: Union[str, None] = 'e8e612087328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'sessions',
    sa.Column('role', sa.String(), nullable=False, server_default='student')
)
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('sessions', 'context')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'ended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('context', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'role')
    # ### end Alembic commands ###
