"""add audio_path and status to sessions

Revision ID: e8e612087328
Revises: 13ac347d6752
Create Date: 2025-10-28 15:08:38.433385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e612087328'
down_revision: Union[str, None] = '13ac347d6752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('audio_path', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'status')
    op.drop_column('sessions', 'audio_path')
    # ### end Alembic commands ###
